[package]
name = "sdac"
version = "0.1.0"
authors = ["The SDAC Authors"]
license = "MIT"
description = "Software Defined Acclerated Compute"
homepage = "https://github.com/xertai/sdac"
edition = "2021"
build = "build-cuda-driver.rs"

[build-dependencies]
bindgen = "0.63.0"
