[package]
name = "sdac"
version = "0.1.0"
authors = ["The SDAC Authors"]
license = "MIT"
description = "Software Defined Acclerated Compute"
homepage = "https://github.com/xertai/sdac"
edition = "2021"

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
