name: "Compulify CLA Bot"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "Computelify CLA Bot"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: '.github/cla/v1/signatures.json'
          path-to-document: '.github/cla/v1/COMPUTELIFYCLA.md'
          branch: 'main'
          allowlist: user1,bot*
          signed-commit-message: 'For example: $contributorName has signed the Computelify CLA in #$pullRequestNo'
          custom-notsigned-prcomment: 'Welcome to a XertAI project! XertAI is managed by Computelify. To ensure your work is properly protected, we ask that you sign the Computelify CLA.'
          custom-allsigned-prcomment: 'PogChamp! Thank you for signing the Computelify CLA **ALL CONTRIBUTORS HAVE SIGNED CLA**'
