name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Retrieve CUDA keyring
      run: wget https://developer.download.nvidia.com/compute/cuda/repos/debian11/x86_64/cuda-keyring_1.0-1_all.deb
    - name: Install CUDA Keyring
      run: sudo dpkg -i cuda-keyring_1.0-1_all.deb
    - name: Download CUDA Driver Developement Headers (12.0)
      run: wget https://developer.download.nvidia.com/compute/cuda/repos/debian11/x86_64/cuda-driver-dev-12-0_12.0.107-1_amd64.deb
    - name: Install CUDA Driver Development Headers (12.0)
      run: sudo dpkg -i cuda-driver-dev*
    - name: Lint
      run: cargo clippy --verbose
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
