# Spellcheck workflow configuraiton
# Documented in depth:
# - https://github.com/marketplace/actions/github-spellcheck-action

name: spellcheck
on:
  pull_request:
jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@0.29.0
      name: Spellcheck
      with:
        config_path: .github/config/spellcheck.yml
        task_name: Markdown
        output_file: spellcheck-output.txt
